source ~/dotfiles/vim/vimPlugins.vim
"set syntax options
source ~/dotfiles/vim/vimJavascript.vim
"set colors
source ~/dotfiles/vim/colors/alduin.vim

"theme options
let t:is_transparent = 0
function! Toggle_transparent()
    if t:is_transparent == 0
        hi Normal guibg=NONE ctermbg=NONE
        let t:is_transparent = 1
    else
        set background=dark
        let t:is_tranparent = 0
    endif
endfunction
nnoremap <F9> : call Toggle_transparent()<CR>

no <down> <Nop>
no <left> <Nop>
no <right> <Nop>
no <up> <Nop>

ino <down> <Nop> 
ino <left> <Nop>
ino <right> <Nop>
ino <up> <Nop>

"nerdtree mappings
noremap <F2> :NERDTree<CR>

"syntastic options
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

