let mapleader="\<Space>"

"source plugins
source ~/dotfiles/vim/vimPlugins.vim
source ~/dotfiles/vim/vimMappings.vim

set nocompatible
filetype plugin on
syntax on

no <down> <Nop>
no <left> <Nop>
no <right> <Nop>
no <up> <Nop>

ino <down> <Nop> 
ino <left> <Nop>
ino <right> <Nop>
ino <up> <Nop>

setlocal spell spelllang=en
set nospell
set relativenumber
set number

"nerdtree mappings
noremap <F2> :NERDTree<CR>

"shortcuts
noremap <C-s> :w<CR>
inoremap <C-s> <Esc>:w<CR>

"syntastic options
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

nnoremap <leader>sc :source %<CR>
