#aliases
alias mc='. /usr/share/mc/bin/mc-wrapper.sh'
alias bo='gedit ~/.bashrc'
alias o='open'
alias changeBrightness='xrandr --output eDP-1 --brightness'

#custom functions 

function open () {
  xdg-open "$@">/dev/null 2>&1
}


