echo "Loading shell.."
#paths and exports
export EDITOR="/usr/bin/vim"
export ZSH_CUSTOM="~/dotfiles/zsh"
ZSH_CUSTOM="~/dotfiles/zsh"

#aliases
alias o='open'
alias cw='wal -i ~/Pictures/wal/'
alias sai='sudo apt-get install'
alias q='exit'
alias rm='rm -i'
alias music='ncmpcpp'
alias mux='tmuxinator'
alias sourcezsh='. ~/.zshrc'
alias sz='. ~/.zshrc'

alias setclip="xclip -selection c"
alias getclip="xclip -selection c -o"


# typos
alias claer='clear'
alias l='ls'

# zsh bindings
bindkey '^ ' autosuggest-accept

# git stuff

alias gs='git status'
alias gc='git checkout'
alias gcd='git checkout develop'
alias gpl='git pull origin HEAD'
alias gcm='git commit -m'
alias gcnb='git checkout -b'
alias gaa='git add .'
alias gpo='git push origin HEAD'

# dev
alias rs='rails s -p 5000'
alias ws='bin/webpack-dev-server'
alias ys='yarn storybook'

#custom functions

function open () {
  xdg-open "$@">/dev/null 2>&1
}

function sai() {
  sudo apt-get install "$@">/dev/null 2>&1
}

#easier calculations

#disable control flow
stty -ixon

#pywal
# (cat ~/.cache/wal/sequences &)
# source ~/.cache/wal/colors-tty.sh

#plugins
source "$HOME/.vim/bundle/gruvbox/gruvbox_256palette.sh"

# paths
export LOVE_PATH="/Applications/love.app/Contents/MacOS/"
export PATH="${PATH}:${LOVE_PATH}"

plugins=(
  zsh-autosuggestions
)
